"use strict";var w=Object.defineProperty;var M=Object.getOwnPropertyDescriptor;var O=Object.getOwnPropertyNames;var L=Object.prototype.hasOwnProperty;var C=(i,n)=>{for(var s in n)w(i,s,{get:n[s],enumerable:!0})},F=(i,n,s,t)=>{if(n&&typeof n=="object"||typeof n=="function")for(let e of O(n))!L.call(i,e)&&e!==s&&w(i,e,{get:()=>n[e],enumerable:!(t=M(n,e))||t.enumerable});return i};var P=i=>F(w({},"__esModule",{value:!0}),i);var B={};C(B,{default:()=>v});module.exports=P(B);var h=require("obsidian"),u=require("fs"),p=require("path"),D=require("child_process"),d=require("os"),R=!!process.env.FLATPAK_ID||(0,u.existsSync)("/.flatpak-info"),k,U=R?(0,p.join)((0,d.homedir)(),".config"):(k=process.env.XDG_CONFIG_HOME)!=null?k:(0,p.join)((0,d.homedir)(),".config"),W=(0,p.join)(U,"wrapweb","plugins","routing","routing.json"),x=null;function _(){let i=Date.now();if(x&&i-x.ts<1e3)return x.data;try{let n=JSON.parse((0,u.readFileSync)(W,"utf8"));return x={ts:i,data:n},n}catch(n){return{}}}function m(){var n;let i=((n=process.env.XDG_DATA_DIRS)!=null?n:"/usr/local/share:/usr/share").split(":").filter(Boolean);return[(0,p.join)((0,d.homedir)(),".local","share"),...i]}function T(i,n=!1){if(!i)return null;let s=m().map(t=>(0,p.join)(t,"icons","hicolor"));for(let t of s){if(n){let e=(0,p.join)(t,"scalable","apps",`${i}.svg`);if((0,u.existsSync)(e))return e}for(let e of["48x48","32x32","64x64","256x256","128x128"]){let o=(0,p.join)(t,e,"apps",`${i}.png`);if((0,u.existsSync)(o))return o}}for(let t of m()){let e=(0,p.join)(t,"pixmaps",`${i}.png`);if((0,u.existsSync)(e))return e}return null}function A(i){try{return`data:${i.endsWith(".svg")?"image/svg+xml":"image/png"};base64,${(0,u.readFileSync)(i,"base64")}`}catch(n){return null}}function H(i){let n=[(0,p.join)((0,d.homedir)(),".config","mimeapps.list"),...m().map(t=>(0,p.join)(t,"applications","mimeapps.list")),"/etc/xdg/mimeapps.list"],s=null;for(let t of n)if((0,u.existsSync)(t))try{let e=(0,u.readFileSync)(t,"utf8").split(`
`),o="";for(let l of e){let a=l.trim();if(a.startsWith("[")){o=a;continue}if(o!=="[Default Applications]"&&o!=="[Added Associations]")continue;let r=a.indexOf("=");if(r===-1||a.slice(0,r)!==i)continue;let c=a.slice(r+1).split(";")[0].trim();if(c){if(o==="[Default Applications]")return c;s||(s=c)}}}catch(e){}if(s)return s;for(let t of m()){let e=(0,p.join)(t,"applications","mimeinfo.cache");if((0,u.existsSync)(e))try{let o=(0,u.readFileSync)(e,"utf8").split(`
`),l=!1;for(let a of o){let r=a.trim();if(r==="[MIME Cache]"){l=!0;continue}if(r.startsWith("[")){l=!1;continue}if(!l)continue;let c=r.indexOf("=");if(c!==-1&&r.slice(0,c)===i){let f=r.slice(c+1).split(";")[0].trim();if(f)return f}}}catch(o){}}return null}function S(i){try{let n=H(i);if(!n)return null;let s=m().map(o=>(0,p.join)(o,"applications")),t=n.replace(/\.desktop$/,"");for(let o of s)try{let l=(0,u.readFileSync)((0,p.join)(o,n),"utf8").match(/^Icon=(.+)$/m);if(l){t=l[1].trim();break}}catch(l){}let e=T(t);return e?A(e):null}catch(n){return null}}var b;function y(){return b!==void 0?b:b=S("x-scheme-handler/https")}var E=new Map;function $(i){if(E.has(i))return E.get(i);let n=(0,p.basename)(i).replace(/\.(AppImage|appimage)$/,""),s=T(n,!0),t=s?A(s):null;return E.set(i,t),t}function I(i){let n,s;try{({hostname:n,pathname:s}=new URL(i))}catch(r){return null}let t=_(),e=Object.entries(t).sort((r,c)=>c[0].length-r[0].length).find(([r])=>{let c=r.indexOf("/");if(c!==-1){let f=r.slice(0,c),g="/"+r.slice(c+1);return(n===f||n.endsWith("."+f))&&s.startsWith(g)}return n===r||n.endsWith("."+r)});if(!e)return null;let o=e[1],l=typeof o=="string"?o:o.path;if(!(0,u.existsSync)(l))return null;let a=typeof o=="object"&&o.name?o.name:(0,p.basename)(l).replace(/^wrapweb-/,"").replace(/-/g," ");return{appImagePath:l,name:a,iconDataUrl:$(l)}}function j(i,n){var l;let[s,t]=R?["flatpak-spawn",["--host",i.appImagePath,"--no-sandbox",n]]:[i.appImagePath,["--no-sandbox",n]],e=(0,D.spawn)(s,t,{detached:!0,stdio:"pipe"}),o="";(l=e.stderr)==null||l.on("data",a=>{o+=a.toString()}),e.on("error",a=>console.log("[wrapweb] spawn error:",a.message)),e.on("close",a=>{a&&o.includes("org.freedesktop.Flatpak")&&new h.Notice(`wrapweb: Run this once to allow opening apps from Obsidian Flatpak:
flatpak override --user --talk-name=org.freedesktop.Flatpak md.obsidian.Obsidian`,12e3)}),e.unref(),new h.Notice(`Opening in ${i.name} \u2026`)}function G(i,n){let s=/\[([^\]]*)\]\((https?:\/\/[^)]*)\)/g,t;for(;(t=s.exec(i))!==null;)if(n>=t.index&&n<=t.index+t[0].length)return t[2];let e=/https?:\/\/[^\s)>\]"]*/g;for(;(t=e.exec(i))!==null;)if(n>=t.index&&n<=t.index+t[0].length)return t[0];return null}var X=`
#wrapweb-link-tooltip {
  position: fixed; bottom: 0; left: 50%; transform: translateX(-50%);
  z-index: 2147483647; max-width: 60%; padding: 3px 10px 4px;
  font: 12px/1.5 -apple-system, system-ui, sans-serif; color: #fff;
  background: rgba(30,30,30,0.85); border-top-left-radius: 5px;
  border-top-right-radius: 5px; pointer-events: none; display: none;
  backdrop-filter: blur(4px); align-items: center; gap: 6px; min-width: 0;
}
#wrapweb-link-tooltip img { width:14px; height:14px; flex-shrink:0; object-fit:contain; }
#wrapweb-link-tooltip span { white-space:nowrap; overflow:hidden; text-overflow:ellipsis; min-width:0; }
`,v=class extends h.Plugin{constructor(){super(...arguments);this.tipEl=null;this.tipIcon=null;this.tipLabel=null;this.styleEl=null}async onload(){this.styleEl=document.head.createEl("style"),this.styleEl.textContent=X,this.tipEl=document.body.createEl("div"),this.tipEl.id="wrapweb-link-tooltip",this.tipIcon=this.tipEl.createEl("img"),this.tipIcon.alt="",this.tipIcon.style.display="none",this.tipLabel=this.tipEl.createEl("span"),setTimeout(()=>y(),0),this.registerDomEvent(document,"click",this.onClick.bind(this),{capture:!0}),this.registerDomEvent(document,"mouseover",this.onMouseover.bind(this),{capture:!0})}onunload(){var s,t;(s=this.tipEl)==null||s.remove(),(t=this.styleEl)==null||t.remove(),this.tipEl=null,this.tipIcon=null,this.tipLabel=null,this.styleEl=null}urlFromEvent(s){var o,l,a;let t=s.target,e=(o=t.closest)==null?void 0:o.call(t,"a.external-link");if(e)return e.href;if((l=t.closest)!=null&&l.call(t,".cm-link")){let r=this.app.workspace.getActiveViewOfType(h.MarkdownView),c=(a=r==null?void 0:r.editor)==null?void 0:a.cm;if(c){let f=c.posAtCoords({x:s.clientX,y:s.clientY},!1);if(f!=null){let g=c.state.doc.lineAt(f);return G(g.text,f-g.from)}}}return null}onClick(s){if(s.button!==0)return;let t=this.urlFromEvent(s);if(!t||!t.startsWith("http://")&&!t.startsWith("https://"))return;let e=I(t);e&&(s.preventDefault(),s.stopImmediatePropagation(),this.hideTooltip(),j(e,t))}onMouseover(s){let t=this.urlFromEvent(s);if(!t||!t.startsWith("http://")&&!t.startsWith("https://")){this.hideTooltip();return}let e=I(t),o=e?e.iconDataUrl:y();this.showTooltip(o,t)}showTooltip(s,t){!this.tipEl||!this.tipIcon||!this.tipLabel||(s?(this.tipIcon.src=s,this.tipIcon.style.display=""):this.tipIcon.style.display="none",this.tipLabel.textContent=t,this.tipEl.style.display="flex")}hideTooltip(){this.tipEl&&(this.tipEl.style.display="none")}};
